//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_chat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public int idCarta { get; set; }
        public string nombreCarta { get; set; }
        public string rutaImagenCarta { get; set; }
    }
}
