//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JuegoLoterestEntities : DbContext
    {
        public JuegoLoterestEntities()
            : base("name=JuegoLoterestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Baraja> Baraja { get; set; }
        public virtual DbSet<Carta> Carta { get; set; }
        public virtual DbSet<Juego> Juego { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<Logro> Logro { get; set; }
        public virtual DbSet<MensajeChat> MensajeChat { get; set; }
        public virtual DbSet<Puntaje> Puntaje { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Tablero> Tablero { get; set; }
    }
}
