//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public int idJugador { get; set; }
        public string nombreJugador { get; set; }
        public string correoElectronicoJugador { get; set; }
        public string contraseñaJugador { get; set; }
        public Nullable<int> confirmacionJugador { get; set; }
        public string codigoJugador { get; set; }
    }
}
