//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logro
    {
        public int idLogro { get; set; }
        public string nombreLogro { get; set; }
        public string descripcionLogro { get; set; }
        public string rutaImagenLogro { get; set; }
        public int desbloqueoLogro { get; set; }
    }
}
